"""Centralized v1.2 error-code model.

New code may use :func:`error_result`; legacy tools keep their existing
string error shape so existing clients are not broken.
"""

from __future__ import annotations

from typing import Any, Optional

# Profiles / registry
PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
PROFILE_ID_CONFLICT = "PROFILE_ID_CONFLICT"
PROFILE_IN_USE = "PROFILE_IN_USE"
BUILTIN_PROFILE_PROTECTED = "BUILTIN_PROFILE_PROTECTED"
INVALID_PROFILE = "INVALID_PROFILE"

# Source safety
SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
SOURCE_CHANGED = "SOURCE_CHANGED"
SOURCE_OUTPUT_PATH_CONFLICT = "SOURCE_OUTPUT_PATH_CONFLICT"

# Preservation
CONTENT_PRESERVATION_FAILED = "CONTENT_PRESERVATION_FAILED"

# Edit engine
EDIT_TARGET_NOT_FOUND = "EDIT_TARGET_NOT_FOUND"
EDIT_OCCURRENCE_MISMATCH = "EDIT_OCCURRENCE_MISMATCH"
EDIT_COMPLEX_BOUNDARY_UNSUPPORTED = "EDIT_COMPLEX_BOUNDARY_UNSUPPORTED"
EDIT_CONTRACT_VIOLATION = "EDIT_CONTRACT_VIOLATION"
EDIT_OPERATION_CONFLICT = "EDIT_OPERATION_CONFLICT"
EDIT_UNSAFE_DELETE_TARGET = "EDIT_UNSAFE_DELETE_TARGET"
EDIT_UNSUPPORTED_OPERATION = "EDIT_UNSUPPORTED_OPERATION"

# Assembly
ASSEMBLY_INCOMPLETE = "ASSEMBLY_INCOMPLETE"
JOB_CONFIGURATION_CHANGED = "JOB_CONFIGURATION_CHANGED"
CHECKPOINT_SOURCE_CHANGED = "CHECKPOINT_SOURCE_CHANGED"
JOB_NOT_FOUND = "JOB_NOT_FOUND"
ASSEMBLY_PROFILE_NOT_FOUND = "ASSEMBLY_PROFILE_NOT_FOUND"
ITEM_PRESERVATION_FAILED = "ITEM_PRESERVATION_FAILED"

# Template registry
TEMPLATE_ID_CONFLICT = "TEMPLATE_ID_CONFLICT"
TEMPLATE_PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
NO_TEMPLATE_PLACEHOLDERS = "NO_TEMPLATE_PLACEHOLDERS"
MACRO_REJECTED = "MACRO_REJECTED"
UNSAFE_EXTERNAL_RELATIONSHIPS = "UNSAFE_EXTERNAL_RELATIONSHIPS"
MALFORMED_DOCX = "MALFORMED_DOCX"
ALIAS_CONFLICT = "ALIAS_CONFLICT"


def error_result(code: str, message: str, details: Optional[Any] = None) -> dict:
    """Build a consistent v1.2 structured error payload."""
    error: dict[str, Any] = {"code": code, "message": message}
    if details is not None:
        error["details"] = details
    return {"status": "error", "error": error}
